### ISSUE TITLE
Opening .txt file without any newlines gives "unknown document format" error

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#4] opened 2014-11-13 14:09 UTC
For more information see https://github.com/koreader/koreader/issues/1161

**Comment by Hzj-jie** [comment] 2016-04-11 09:26
I would like to revisit this issue, the logic around https://github.com/koreader/crengine/blob/master/crengine/src/lvxml.cpp#L2616, is, sorry, fucking senseless.
And as an ebook reader, the restriction is also too strict. I have spent several hours today to debug a txt book, which unfortunately contains one invalid utf-8 character. The file works well on VI, notepad2, kindle, gedit, even windows notepad. But crengine just returns 'error: unknown format ...'.

A draft plan is to add a LVTextRobustParser, to replace 'error: unknown format ...' message.

**Comment by houqp** [comment] 2016-04-11 09:40
Go ahead :)

Also, you said you are in PST, but you are still awake... Are you jet lagging right now? ;P

**Comment by Hzj-jie** [comment] 2016-04-11 18:08
Ah, not really, I just could not stop debugging the case.

**Comment by poire-z** [comment] 2019-12-06 17:04
Can't reproduce, so probably fixed by #39.

**Closed by poire-z** 2019-12-06 17:04 UTC

**Comment by Hzj-jie** [comment] 2019-12-06 18:50
Thank you for cleaning up this bug. Yes, it should be fixed already, currently we are always using utf-8 if the encoding is unknown.
